#!/usr/bin/env python
import sys, os, string, time
from pprint import pprint

################ Interactive Prompt and Debugging ################

try:
    import readline
except ImportError:
  pass
else:
    import rlcompleter
    if 'libedit' in readline.__doc__:
        readline.parse_and_bind("bind ^I rl_complete")
    else:
        readline.parse_and_bind("tab: complete")
